#preload = /usr/share/theme/bg-1.png
#wallpaper = eDP-1, /usr/share/theme/bg-1.png

wallpaper {
    monitor =
    path = ~/wallpapers/VRChat_2025-09-25_22-59-19.779_4320x7680_wrld_5053502f-6fcc-4951-8299-ce6e9aad5ae5_cropped.png
}

