preload = /usr/share/theme/bg-1.png
preload = /home/cyan/Pictures/VRChat/2025-05/VRChat_2025-05-13_00-24-22.464_3840x2160.compressed.png
wallpaper = HDMI-A-1, /usr/share/theme/bg-1.png
wallpaper = DP-1, /usr/share/theme/bg-1.png
#wallpaper = HDMI-A-1, /home/cyan/Pictures/VRChat/2025-05/VRChat_2025-05-13_00-24-22.464_3840x2160.compressed.png
#wallpaper = DP-1, /home/cyan/Pictures/VRChat/2025-05/VRChat_2025-05-13_00-24-22.464_3840x2160.compressed.png
